# Generated by Django 5.2.7 on 2026-02-07 11:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('storage_file_name', models.CharField(max_length=50, unique=True)),
                ('native_file_name', models.CharField(max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('last_download_date', models.DateField(null=True)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('public_download_id', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='storage'), upload_to='')),
            ],
        ),
    ]
