# Generated by Django 5.2.7 on 2025-10-29 19:35

import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=storage.models.user_directory_path)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('share_link', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
